
DROP TABLE IF EXISTS user_vote;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS attachment;
DROP TABLE IF EXISTS poll;
DROP TABLE IF EXISTS lecture;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    PRIMARY KEY (username)
);


CREATE TABLE IF NOT EXISTS user_roles (
    user_role_id INTEGER GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_role_id),
    FOREIGN KEY (username) REFERENCES users(username)
);


create table if not exists lecture (
    id bigint generated by default as identity,
    lecture_title varchar(255),
    primary key (id)
);


create table if not exists attachment (
    id uuid default random_uuid() not null,
    content blob,
    content_type varchar(255),
    filename varchar(255),
    lecture_id bigint,
    primary key (id),
    foreign key (lecture_id) references lecture
);


create table if not exists poll (
    id bigint generated by default as identity,
    question varchar(255),
    option_a varchar(255),
    option_b varchar(255),
    option_c varchar(255),
    option_d varchar(255),
    count_a int default 0,
    count_b int default 0,
    count_c int default 0,
    count_d int default 0,
    primary key (id)
);


create table if not exists user_vote (
    id bigint generated by default as identity,
    username varchar(50) not null,
    poll_id bigint not null,
    vote_option varchar(1) not null,
    primary key (id),
    foreign key (username) references users(username),
    foreign key (poll_id) references poll(id),
    unique (username, poll_id)
);
