DROP TABLE IF EXISTS lecture_comments;
drop table if exists attachment;
drop table if exists lecture;



create table if not exists lecture (
                                       id bigint generated by default as identity,
                                       lecture_title varchar(255),
                                       primary key (id)
);
create table if not exists attachment (
                                          id uuid default random_uuid() not null,
                                          content blob,
                                          content_type varchar(255),
                                          filename varchar(255),
                                          lecture_id bigint,
                                          primary key (id),
                                          foreign key (lecture_id) references lecture
);

DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
                                     username VARCHAR(50) NOT NULL,
                                     password VARCHAR(50) NOT NULL,
                                     PRIMARY KEY (username)
);
CREATE TABLE IF NOT EXISTS user_roles (
                                          user_role_id INTEGER GENERATED ALWAYS AS IDENTITY,
                                          username VARCHAR(50) NOT NULL,
                                          role VARCHAR(50) NOT NULL,
                                          PRIMARY KEY (user_role_id),
                                          FOREIGN KEY (username) REFERENCES users(username)
);



CREATE TABLE IF NOT EXISTS lecture_comments(
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lecture_id BIGINT NOT NULL,
    username VARCHAR(50) NOT NULL,
    comment_text VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (comment_id),
    FOREIGN KEY (lecture_id) REFERENCES lecture(id),
    FOREIGN KEY (username) REFERENCES users(username)
    );